# Generated by Django 2.1.3 on 2019-04-09 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_awarded', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('subjective_answer', models.TextField(blank=True, default='', null=True)),
                ('response_A', models.TextField(blank=True, default='', null=True)),
                ('response_B', models.TextField(blank=True, default='', null=True)),
                ('response_C', models.TextField(blank=True, default='', null=True)),
                ('response_D', models.TextField(blank=True, default='', null=True)),
                ('is_attempted', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('current_time', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_attempted', models.BooleanField(default=False)),
                ('total_marks_obtained', models.IntegerField(blank=True, null=True)),
                ('total_subjective_marks', models.IntegerField(blank=True, null=True)),
                ('total_objective_positive', models.IntegerField(blank=True, null=True)),
                ('total_objective_negative', models.IntegerField(blank=True, null=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
            options={
                'verbose_name': 'AnswerSheet',
                'verbose_name_plural': 'AnswerSheets',
                'db_table': 'AnswerSheets',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.AnswerSheet'),
        ),
    ]
