# Generated by Django 2.1.7 on 2019-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20190411_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='total_marks_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
