# Generated by Django 2.1.3 on 2019-04-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_answersheet_total_marks_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='start_time',
        ),
        migrations.AddField(
            model_name='answer',
            name='response_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
